### ISSUE TITLE
Broken with newest ftw.shop

### ISSUE THREAD

**Issue by jone** [4teamwork/ftwshop.simplelayout#19]
Since https://github.com/4teamwork/ftw.shop/pull/65 was merged, the tests for ftwshop.simplelayout are broken:

```
  File "/var/lib/jenkins/jobs/ftwshop.simplelayout/workspace@2/ftwshop/simplelayout/browser/shopitemblock.py", line 2, in <module>
    from ftw.shop.browser.shopitem import ShopCompactItemView
ZopeXMLConfigurationError: File "<string>", line 1.109-1.143
    ZopeXMLConfigurationError: File "/var/lib/jenkins/jobs/ftwshop.simplelayout/workspace@2/ftwshop/simplelayout/configure.zcml", line 13.2-13.32
    ZopeXMLConfigurationError: File "/var/lib/jenkins/jobs/ftwshop.simplelayout/workspace@2/ftwshop/simplelayout/browser/configure.zcml", line 12.4-16.34
    ImportError: cannot import name ShopCompactItemView
```

@shylux can you fix this?

**Comment by maethu** [comment]
@shylux Please fix this regression as soon as you work the next time with ftw.shop

**Comment by shylux** [comment]
With https://github.com/4teamwork/ftw.shop/pull/65 the `ShopCompactItemView` was made the default view and the previous default view got removed (because it was broken for quite a while and nobody cared). Updating the classes should probably fix this problem already.
